### ISSUE TITLE
Migrate to use Rudder

### ISSUE THREAD

**Issue by larkox** [mattermost/mattermost-plugin-nps#64]
The server is now using analytics through Rudder instead of Segment.

We should migrate this plugin to register the analytics through Rudder instead of Segment.

**Comment by hanzei** [comment]
This change has to be done before Segment get's disabled, right?

**Comment by larkox** [comment]
No. Segment will not be shut down due to support for old server versions. What will be disabled is the connection from the newer versions to segment (newer versions will not report to segment).

Therefore, this is not an urgent matter (we will not lose any information for not updating it, at least on short-mid term). But it is something that has to be done eventually.

**Comment by hanzei** [comment]
Got it. Thanks for the explanation. :+1:
